### ISSUE TITLE
Paper suggestions / questions

### ISSUE THREAD

**Issue by deniederhut** [ORNL/tx2#1] opened 2021-10-29 01:31 UTC
- In the summary, instead of saying the library "assumes the use" of HuggingFace, I might say that in that first sentence that it's built for understanding the behavior of HuggingFace transformer models
- In the introduction, you mention the Attention is not Explanation paper (awesome), but this method is attention-based, no?
- I think we're missing a reference to the Vaswani 2017 paper
- I was expecting to see a reference to https://github.com/jessevig/bertviz here -- is there a reason it wasn't included?
- I tend to prefer journal references over arxiv when available. Leland lists JOSS in the "how to cite" section for UMAP (it was also presented at SciPy the same year https://www.youtube.com/watch?v=nq6iPZVUxZU, but alas no paper)
- You can find guidance on how to cite Jupyter here: https://github.com/jupyter/jupyter/issues/190
- scikit-learn also has guidance for citations https://scikit-learn.org/stable/about.html#citing-scikit-learn
- I don't know that I would agree with "These users will also tend to perform some or most of their work within the Jupyter ecosystem" -- there is a rather famous talk about this by a researcher at Allen. I don't think this is a dealbreaker or anything; Jupyter is wildly popular and facilitates interactive exploration, even if you wouldn't have used Jupyter to build the model in the first place.
- On that note, what if I have a fully trained model already? Can I load in a pretrained head? What if the task isn't classification, but regression or a sequence-to-sequence?

**Comment by WildfireXIII** [comment] 2021-11-29 18:43
> In the summary, instead of saying the library "assumes the use" of HuggingFace, I might say that in that first sentence that it's built for understanding the behavior of HuggingFace transformer models

This library doesn't technically need HuggingFace transformers specifically, it's a lot easier and we use them in the example notebooks, but any transformer model for which the user can implement the four interaction functions should technically work.

> In the introduction, you mention the Attention is not Explanation paper (awesome), but this method is attention-based, no?

It's not actually attention-based, our salience map approach is a bit more coarse than that - the "word importance" is calculated by removing each word of a text individually and measuring the change in the predicted output probabilities. (This is also what allows the approach to be relatively model agnostic.) 

> I think we're missing a reference to the Vaswani 2017 paper

Oops, you're right! Fixed!

> I was expecting to see a reference to https://github.com/jessevig/bertviz here

We do reference it in the statement of need section, their repo asked to cite their paper instead, "A Multiscale Visualization of Attention in the Transformer Model", it's the (Vig, 2019) ref.

> I don't know that I would agree with "These users will also tend to perform some or most of their work within the Jupyter ecosystem"

That's fair, I backed off the claim.

> On that note, what if I have a fully trained model already? Can I load in a pretrained head? What if the task isn't classification, but regression or a sequence-to-sequence?

Yes, TX2 doesn't handle any of the training and makes no assumptions about how the training was done, so it's up to the user to provide a fully trained model to TX2. Unfortunately TX2 can only handle exploring the model from a classification task perspective. You could in principle have a model that was originally trained on a regression task, but for the interaction functions TX2 is expecting to make sense (`classify()` and `soft_classify()`), the model has to have some way to provide a classification output and classification probabilities.



Citations for UMAP, Jupyter, and scikit-learn are fixed!

**Comment by deniederhut** [comment] 2021-12-09 02:55
Cool, thanks for adding all those! Three more comments:

1. Each line is numbered. Is that on purpose?
2. I'm listed as the reviewer twice -- hopefully not because I was twice as slow? 😉
3. I don't recall seeing the copyright disclaimer last time. Is this okay with JOSS?

**Comment by WildfireXIII** [comment] 2021-12-09 14:31
1. That's a good question, those don't show up when I locally compile it with JOSS's docker container, so I'm assuming that's just part of their draft mode?
2. Oh no haha, that might be a Fabian question, I don't manually insert reviewer names anywhere!
3. Definitely a Fabian question, I believe that section was there when we first submitted, it's in paper.md in the repository commit right before the submission date: https://github.com/ORNL/tx2/blob/60ff3367e3db5b3e0d5fba683d5b4fcb57b0ab33/paper/paper.md. I was told to add that bit I think, the software itself is definitely under a BSD license, but I'm definitely not a lawyer so I don't know what the paper license stuff implies! If this is a potential issue I can ask around about it. (I'll drop a note over in the main thread in the meantime)

**Comment by fabian-s** [comment] 2021-12-09 15:29
@1 I think so, too  
@2 no clue. if this persists at the proofing stage i'll ask the veteran editors  
@3 BSD-3 is fine, JOSS acceps all OSI-approved licenses

**Comment by WildfireXIII** [comment] 2021-12-09 19:52
@fabian-s I think number 3 is referring to the legal jargon line in the acknowledgements section in the paper: https://github.com/ORNL/tx2/blob/master/paper/paper.md?plain=1#L59

@stewartsl do you know where we got that/is it required?

**Comment by fabian-s** [comment] 2021-12-10 09:01
thanks for pointing that out -- should be no problem.

**Comment by WildfireXIII** [comment] 2021-12-15 23:49
Great! It looks like everything is addressed in this issue so I'm gonna close it.

(linking for notification in main thread openjournals/joss-reviews#3652)

**Closed by WildfireXIII** 2021-12-15 23:49 UTC
